version: '1.0.0-{branch}-{build}'
init:
  - git config --global core.autocrlf true
image:
  - Visual Studio 2017
branches:
  only:
    - dev
install:
  - ps: dotnet --info
  - git clone https://github.com/SteeltoeOSS/steeltoe-ci.git -v
  - ps: steeltoe-ci\scripts\appveyor_install.ps1
test_script:
  - ps: dotnet test test\Steeltoe.Tooling.Test
  - ps: dotnet test test\Steeltoe.Cli.Test
build_script:
  - ps: steeltoe-ci\scripts\appveyor_build.ps1
artifacts:
  - path: '**\*.nupkg'
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
deploy:
- provider: NuGet
  skip_symbols: false
  artifact: /.*\.nupkg/
  server: https://www.myget.org/F/steeltoedev/api/v2/package
  symbol_server: https://www.myget.org/F/steeltoedev/symbols/api/v2/package
  api_key:
    secure: 246ApObnMYYvzDo9Ki72CxxuKfuoqYbrbUK2HLevGIGHXYY6f0OkAdE3EWCwNJ7g
  on:
    branch: dev
    appveyor_repo_tag: false
