version: '0.0.1-{branch}-{build}'
init:
  - git config --global core.autocrlf true
image:
  - Visual Studio 2017
branches:
  only:
    - dev
    - springone-2018
install:
  - ps: dotnet --info
test_script:
  - ps: scripts\unit-test
build_script:
  - ps: dotnet pack --configuration $env:BUILD_TYPE /p:Version=$env:APPVEYOR_BUILD_VERSION --include-symbols --include-source
artifacts:
  - path: '**\*.nupkg'
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
deploy:
- provider: NuGet
  skip_symbols: false
  artifact: /.*\.nupkg/
  server: https://www.myget.org/F/steeltoedev/api/v2/package
  symbol_server: https://www.myget.org/F/steeltoedev/symbols/api/v2/package
  api_key:
    secure: 246ApObnMYYvzDo9Ki72CxxuKfuoqYbrbUK2HLevGIGHXYY6f0OkAdE3EWCwNJ7g
  on:
    branch: springone-2018
    appveyor_repo_tag: false
