language: csharp
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
mono: none
dotnet: 2.1.300
os:
  - linux
  - osx
branches:
  only:
    - dev
script:
  - dotnet --info
  - dotnet build
  - scripts/unit-test
  - scripts/cli-test
  - dotnet pack
