language: csharp
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
mono: none
dotnet: 2.1.300
os:
  - linux
  - osx
osx_image: xcode8.3
branches:
  only:
    - master
script:
  - dotnet --info
  - dotnet test test\Steeltoe.Tooling.Test
  - dotnet pack
