trigger:
- master
- dev

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  PackageVersion: $[format('0.5.0-{0}', variables['Build.BuildId'])]

jobs:
- job: Linux_Build_and_Test
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/Tooling.sln'
      arguments: '--configuration Release'
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: '**/test/**/*Test.csproj'
- job: MacOS_Build_and_Test
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/Tooling.sln'
      arguments: '--configuration Release'
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: '**/test/**/*Test.csproj'
- job: Windows_Build_and_Test
  pool:
    vmImage: 'Windows-2019'
  steps:
  - task: DotNetCoreCLI@2
    displayName: Pack
    inputs:
      command: 'pack'
      arguments: '---no-restore -c $(buildConfiguration) /p:TreatWarningsAsErrors=True'
      packagesToPack: 'Tooling.sln'
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'PackageVersion'
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: '**/test/**/*Test.csproj'
      arguments: '--configuration $(buildConfiguration)'
