trigger:
- master
- dev

variables:
  Solution: 'Tooling'
  PackageVersion: $[format('0.5.0-{0}', variables['Build.BuildId'])]
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
- job: 'Linux'
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - task: 'DotNetCoreCLI@2'
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: '$(Solution).sln'
      arguments: '--configuration Release /p:TreatWarningsAsErrors=True'
  - task: 'DotNetCoreCLI@2'
    displayName: 'Test'
    inputs:
      command: 'test'
      projects: '$(Solution).sln'
- job: 'OSX'
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - task: 'DotNetCoreCLI@2'
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: '$(Solution).sln'
      arguments: '--configuration Release /p:TreatWarningsAsErrors=True'
  - task: 'DotNetCoreCLI@2'
    displayName: 'Test'
    inputs:
      command: 'test'
      projects: '$(Solution).sln'
- job: 'Windows'
  pool:
    vmImage: 'Windows-2019'
  steps:
  - task: 'DotNetCoreCLI@2'
    displayName: 'Pack'
    inputs:
      command: 'pack'
      packagesToPack: '$(Solution).sln'
      arguments: '--configuration Release /p:TreatWarningsAsErrors=True'
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'PackageVersion'
  - task: 'DotNetCoreCLI@2'
    displayName: 'Test'
    inputs:
      command: 'test'
      projects: '$(Solution).sln'
