#!/usr/bin/env bash

toolProject=Steeltoe.Tooling.DotnetCli

cd $(dirname $0)/..

dotnet tool uninstall --global $toolProject
dotnet pack
dotnet tool install --global --add-source src/$toolProject/bin/Debug $toolProject
