#!/usr/bin/env bash

toolProject=Steeltoe.Tooling.DotnetCli

basedir=$(dirname $0)/..

cd $basedir
dotnet tool uninstall --global $toolProject
dotnet pack
dotnet tool install --global --add-source src/$toolProject/bin/Debug $toolProject
