= Steeltoe Tooling: Theory of Operations
How to setup and run the sample tests.
:uri-api-src: ../src/Steeltoe.Tooling
:uri-cli-src: ../src/Steeltoe.Cli
:toc:

== Overview

Steeltoe Tooling is comprised of 3 layers:

API::  Tooling operations and workflows

UI:: Interface with which users interact; sits on top of the API

Drivers:: Orchestrates application and service deployment; used by the API

== Components

=== API

The Steeltoe Tooling API provides a programmatic interface into Tooling functionality.

The API defines link:{uri-api-src}/Executor[workflow abstractions] intended to be used by UIs.

The API also defines the object model to be used in creating additional workflow abstractions, or as an integration point in cases where the available workflow abstractions are not sufficient.

=== UIs

The only current user interface is the link:{uri-cli-src}[Steeltoe CLI].

Future UIs may include extensions to Visual Studio and JetBrains Rider.

A UI's job is to be a bridge between a UI, such as a CLI or IDE, and the Steeltoe API (and in particular, Steeltoe API workflows).

=== Drivers

Integration with deployment targets is achieved using implementations of an link:{uri-api-src}/IDriver.cs[IDriver.cs].  A driver's job is relatively simple in scope: deploy and undeploy applications and services, and report lifecycle states of those applications and services.

== Key Concepts

=== Registry

link:{uri-api-src}/Registry.cs[Registry.cs] defines services available to Steeltoe Tooling.
Service definitions include basic information about a service, such as the service name and port.
The registry also defines services in the context of a driver.  E.g., for the Docker driver, the service definition includes the Docker image name.

The service definitions are loaded from the configuration file link:{uri-api-src}/steeltoe.rc/registry.yml[registry.yml].

=== Lifecycles

The Steeltoe API implements a link:{uri-api-src}/Lifecycle.cs[Lifecycle.cs] of applications and services largely independent of drivers.
A driver's participation in lifecycle management is solely the determination of an application's or service's current lifecycle state.
Lifecycle transitions may or may not be permitted depending on a lifecycle state.
E.g., an application in an _Offline_ state may be deployed whereas an application in a _Starting_ state may not.

.States
Offline:: an item is not deployed
Starting:: an item is in the process of being deployed and is not yet available for use
Online:: an item is fully deployed and available for use
Stopping:: an item is in the process of being undeployed is not available for use
Unknown:: a failsafe for drivers when unable to determine an item's state

.Transitions
Deploy:: deploy an offline item
Undeploy:: undeploy an online item

=== Context

All workflows are executed in an instance of a link:{uri-api-src}/Context.cs[Context.cs] that is constructed prior to execution of the workflow.  The context provides:

* path to project directory
* project configuration
* a console to which output maybe displayed to a UI
* a shell in which commands, such as driver implementation commands, may be run
* the current deployment target
