= Steeltoe Tooling Users Guide
:toc:
:toclevels: 4

== CLI

=== Installing

.install
----
$ dotnet tool install steeltoe.cli --global --add-source https://www.myget.org/F/steeltoedev/api/v3/index.json --version 1.0.0-dev-00146
----

.uninstall
----
$ dotnet tool uninstall --global steeltoe.cli
----

=== Quickstart

==== Deploy to Docker

.checkout Steeltoe Samples and navigate to the Simple project
----
$ git clone https://github.com/SteeltoeOSS/Samples.git
$ cd Samples/Configuration/src/AspDotNetCore/Simple
----

.add Steeltoe Tooling to project
----
$ st init
Initialized Steeltoe Developer Tools
----

.add application and config-server to deployment configuration
----
$ st add app simple
Added app 'simple'

$ st add config-server the-config-server
Added config-server service 'the-config-server'
----

.target Docker for deployment
----
$ st target docker
Docker ... Docker version 18.09.1, build 4c52b90
Docker host OS ... Docker for Mac
Docker container OS ... linux
Target set to 'docker'
----

.deploy
----
$ st deploy
Deploying service 'the-config-server'
Deploying app 'simple'
----

.check status, then navigate to application
----
st status
the-config-server online
simple online
----

Open http://localhost:8080/

.undeploy
----
$ st undeploy
Undeploying app 'simple'
Undeploying service 'the-config-server'
----

==== Deploy to Cloud Foundry

.checkout Steeltoe Samples and navigate to the SimpleCloudFoundry project
----
$ git clone https://github.com/SteeltoeOSS/Samples.git
$ cd Samples/Configuration/src/AspDotNetCore/SimpleCloudFoundry
----

.add Steeltoe Tooling to project
----
$ st init
Initialized Steeltoe Developer Tools
----

.add application and config-server to deployment configuration
----
$ st add app simple-cloud-foundry
Added app 'simple-cloud-foundry'

$ st add config-server the-config-server
Added config-server service 'the-config-server'
----

.target CloudFoundry for deployment
----
$ st target cloud-foundry
Cloud Foundry ... cf version 6.42.0+0cba12168.2019-01-10
logged into Cloud Foundry ... yes
Target set to 'cloud-foundry'
----

.deploy
----
$ st deploy
Deploying service 'the-config-server'
Waiting for service 'the-config-server' to come online (1)
Waiting for service 'the-config-server' to come online (2)
Waiting for service 'the-config-server' to come online (3)
...
Waiting for service 'the-config-server' to come online (35)
Deploying app 'simple-cloud-foundry'
----

.check status, then navigate to application
----
$ st status
the-config-server online
simple-cloud-foundry online

$ cf apps
Getting apps in org pivot-ccheetham / space playground as ccheetham@pivotal.io...
OK

name                   requested state   instances   memory   disk   urls
simple-cloud-foundry   started           1/1         512M     1G     simple-cloud-foundry...
                                                                     ^
#                                                                   /
# go to this url  -------------------------------------------------/
#
----

.undeploy
----
$ st undeploy
Undeploying app 'simple-cloud-foundry'
Undeploying service 'the-config-server'
----

== Services

=== Overview

A _service_ is an application that provides a capability (such as data storage) over a network protocol.

.Adding a service using the CLI command:
----
$ st add <type> <name>
----

Where _type_ is a known service type and _name_ is a user-supplied name.

.Service Types
|===
| Type | Description

| config-server | Spring Cloud Config Server
| eureka-server | Netflix Eureka Server
| hystrix-dashboard | Netflix Hystrix Dashboard
| mssql | Microsoft SQL Server
| mysql | MySQL
| redis | Redis Server
| zipkin | Zipkin Tracing Collector and UI
|===


=== Spring Cloud Config Server

https://spring.io/projects/spring-cloud-config[Spring Cloud Config] provides support for externalized configuration.

type:: `config-server`
port:: 8888

.Example
----
$ st add config-server myConfigServer
----

=== Netflix Eureka Server

https://github.com/Netflix/eureka/wiki[Netflix Eureka Server] provides service discovery.

type:: `eureka-server`
port:: 8761

.Example
----
$ st add eureka-server myDiscoveryServer
----

=== Hystrix Dashboard

https://github.com/Netflix/Hystrix/wiki[Hystrix Dashboard] provides latency and fault tolerance.

type:: `hystrix-dashboard`
port:: 8761

.Example
----
$ st add hystrix-dashboard myHystrixDashboard
----

=== Microsoft SQL Server

https://www.microsoft.com/sql-server/[Microsoft SQL Server] provides Microsoft's RDBMS.

type:: `mssql`
port:: 1433

.Example
----
$ st add mssql mySQLServer
----

The SteeltoeOSS Microsoft SQL Docker images (`steeltoeoss/mssql`) require explicit acceptance of the Microsoft EULA.
Acceptance can be specified using a service argument.

.Example accepting EULA in Docker images
----
$ st args -t docker mySQLServer -- --env ACCEPT_EULA=Y
----

=== MySQL

https://www.mysql.com/[MySQL] provides the MySQL RDBMS.

type:: `mysql`
port:: 3306

.Example
----
$ st add mysql myMySQLServer
----

The MySQL Docker images (`steeltoeoss/mssql`) for Linux containers require a MySQL root password to be set.

.Example setting MySQL root password for Linux Docker containers
----
$ st args -t docker myMySQLServer -- --env MYSQL_ROOT_PASSWORD=my-secret-pw
----

=== Redis

https://redis.io/[Redis] provides an in-memory data structure store.

type:: `redis`
port:: 6379

.Example
----
$ st add redis myRedis
----

=== Zipkin Tracing Collector and UI

https://zipkin.io/[Zipkin] provides a distributed tracing system.

type:: `zipkin`
port:: 9411

.Example
----
$ st add zipkin myZipkinCollector
----

== Targets

=== Overview

A _target_ is a deployment environment into which applications and services can be run.

.Setting the deployment target using the CLI:
----
$ st target <target>
----

Where _target_ is a known deployment target.

.Deployment Targets
|===
| Target | Description

| `cloud-foundry` | Cloud Foundry
| `docker` | Docker
|===


=== Cloud Foundry

Pre-requisistes for using Cloud Foundry as a target:

* https://docs.cloudfoundry.org/cf-cli/install-go-cli.html[Cloud Foundry CLI] (`cf` command)
* an account on a Cloud Foundry instance (or derivative such as Pivotal Cloud Foundry)

.Setting Cloud Foundry as the deployment target using the CLI:
----
$ st target cloud-foundry
Cloud Foundry ... cf version 6.42.0+0cba12168.2019-01-10
logged into Cloud Foundry ... yes
Target set to 'cloud-foundry'
----

It is assumed that you are are logged into your Cloud Foundry instance and have selected an _org_ and a _target_.
E.g., running `cf target` should look something like:

----
$ cf target
api endpoint:   https://api.my.cloud.foundry.instance/
api version:    2.98.0
user:           myuser
org:            myorg
space:          myspace
----

=== Docker

Pre-requisistes for using Docker as a target:

* https://docs.docker.com/install/[Docker] installed and running

.Setting Docker as the deployment target using the CLI:
----
$ st target docker
Docker ... Docker version 18.09.1, build 4c52b90
Docker host OS ... Docker for Mac
Docker container OS ... linux
Target set to 'docker'
----
