environment: docker
services:
  steeltoe-config:
    type: config-server
    enabled: true
    args:
      docker: --volume <<CHANGEME>>/servers/ConfigServer/steeltoe/config-repo:/steeltoe/config-repo
  steeltoe-eureka:
    type: eureka
    enabled: true
    args: {}
  steeltoe-hystrix:
    type: hystrix
    enabled: true
    args: {}
  steeltoe-redis:
    type: redis
    enabled: true
    args: {}
  steeltoe-sql-server:
    type: mssql
    enabled: true
    args:
      docker: --env ACCEPT_EULA=Y --env SA_PASSWORD=St33lt03R0cks
  steeltoe-uaa:
    type: uaa
    enabled: true
    args: {}
  steeltoe-zipkin:
    type: zipkin
    enabled: true
    args: {}
